using System;
using System.Collections.Generic;
using System.Text;

namespace Headquartz.Domain.Enums;

/// <summary>
/// Distinguishes events generated by the company's own internal
/// lifecycle/cadence (CompanyAgenda — Grand Opening, Payroll Cycle) from
/// world/market-driven events that fire identically regardless of when
/// the company was founded (SeasonalEvent — holidays, sales periods,
/// black-swan events). Company Agenda items are tied to the company's
/// existence; Seasonal Events are tied to the calendar itself.
/// </summary>
public enum CalendarEventCategory
{
    SeasonalEvent,
    CompanyAgenda,
}